name: Scrape and Commit Playlists

on:
  schedule:
    - cron: '0 */4 * * *'   # Run every 4 hours
  workflow_dispatch:          # Allow manual runs from GitHub Actions tab

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Run PHP script
      run: |
        php scrape_streamed_su.php || exit 1  # Fail workflow if PHP script fails

    - name: Squash and force push changes
      if: success()
      run: |
        # Git identity for commits
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Reset to the first commit
        FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
        git reset --soft $FIRST_COMMIT

        # Add ALL changes (don’t fail if some files don’t exist)
        git add -A

        # Create a single commit if there are changes
        git commit -m "Update playlists" || echo "No changes to commit"

        # Force push to main branch
        git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
